baseURL: https://evraka.havelsan.com.tr/
languageCode: tr-tr
title: EVRAKA Belge Yönetim Sistemi | HAVELSAN
theme: evraka
googleAnalytics:
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
  - identifier: home
    name: "Ana Sayfa"
    url: "/"
    weight: 1
  footer:
  - identifier: diger
    name: "/images/evraka-logo-big.png"
  - identifier: havelsan
    parent: diger
    name: HAVELSAN
    url: https://www.havelsan.com.tr/
    weight: 1
params:
  openGraph: true
  description: HAVELSAN EVRAKA Belge Yönetim Sistemi
  navbarlogo:
    main:
      image: evraka-logo-big.png
    sub:
      image: sub.svg
  hero:
    - title: Belge Yönetim Sistemi
      subtitle: HAVELSAN, kağıda dayalı tüm süreçlerini dijital bir ortama taşımak ve kolay, hızlı ve güvenli doküman paylaşımını sağlamak amacıyla tümüyle yerli ve milli imkânlar ile EVRAKA’yı geliştirmiştir. EVRAKA, kurumların iç yönergelere ve yönetmeliklere uygun olarak belge üretmesini ve belgelerin üretimden tasfiyesine kadar tüm süreçlerini dijital ortamda yönetilmesini sağlar.<br /><br />
      buttons:
        - text: Demo Talebi
          link: "/demo-talebi/"
        - text: Satın Al
          link: "/demo-talebi/"
      image: evraka-side-pic.png
  section_about: 
    video_link: "https://www.youtu.be/yZyScWN2IbQ"
    thumbnail: video-holder.png
    title: Neden EVRAKA?
    text: '“Kaynakların etkin ve verimli kullanılması” ve “Çevreye duyarlılık” ilkelerini kurumsal değerlerinden biri olarak benimsemiş olan HAVELSAN, kâğıda dayalı tüm iş süreçlerini dijital bir ortama taşımak ve kolay, hızlı ve güvenli doküman paylaşımını sağlamak amacıyla tümüyle yerli ve milli imkânlar ile EVRAKA’yı geliştirmiştir.


EVRAKA, kurumların iç yönergelere ve yönetmeliklere uygun olarak belge üretmesini ve belgelerin üretimden tasfiyesine kadar tüm süreçlerini yönetmesini sağlayan; web tabanlı kolay yapılandırılabilir, elektronik ve mobil imza destekli bir 
elektronik doküman ve belge yönetim sistemidir.


EVRAKA, yetkilendirme seviyesine bağlı olarak izlenebilir ve takip edilebilir belge akışı ile ŞEFFAFLIĞI, 
altyapıları ve gelişmiş yetkilendirme yetenekleri ile GÜVENLİĞİ ve dijitalleşen belge süreçleri ile 
kağıt kullanımını azaltarak ÇEVREYE DUYARLILIĞI sağlayan bir sistemdir.
'
  section_features:
    features:
      - list:
          - li: Bilgi yönetimine katkı
          - li: Güçlü altyapı
          - li: Bağımsız veritabanı
          - li: Kurumsal hafıza birikimine katkı
          - li: Standartlara ve yönergelere uyum (TS13298, Askeri Yönergeler, Resmi Yazışmalar, E-İmza)
          - li: İş akışı ile onay süreçlerini izleme
          - li: E-yazışma ile kurumlar arası belge alışverişi
      - list:
          - li: Belgeye hızlı erişim
          - li: Süreçlerin standartlaşması ve kurumsallaşma
          - li: Mobil olarak belge imzalama
          - li: Arşivleme Sürüm Kontrolü ile değişiklikleri izleme
          - li: Yetki yönetimi, E-İmza, şifreleme ve loglama ile güvenli belge yönetimi
          - li: Fiziksel arşivin elektronik ortama aktarımı
          - li: Güçlü entegrasyon desteği
          - li: Mevzuat ve Yönergelere Uygunluk
  footer:
    logo: footer-logo.png
    socialmedia:
      - link: https://github.com/havelsan-tr
        icon: "fab fa-github"
      - link: https://www.havelsan.com.tr/
        icon: "fa fa-globe"
      - link: mailto:info@havelsan.com.tr
        icon: "fa fa-envelope"
module:
  imports:
    path: "github.com/gohugoio/hugo-mod-bootstrap-scss-v4"
